### ISSUE TITLE
Add build timestamp to database

### ISSUE THREAD

**Issue by nponsard** [do4-2022/grobuzin-agent#11]

**Comment by WoodenMaiden** [comment]
I added said field in https://github.com/do4-2022/grobuzin/pull/18/commits/0f21a9c45fd01411e80386089b95054a75df58ae. Is that okay for you?

**Comment by nponsard** [comment]
> I added said field in [do4-2022/grobuzin@0f21a9c](https://github.com/do4-2022/grobuzin/commit/0f21a9c45fd01411e80386089b95054a75df58ae). Is that okay for you?

Good, I'll write the code that updates it tomorrow
